# Generated by Django 4.2.7 on 2023-12-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='filmler/', verbose_name='Film Resmi'),
        ),
    ]
